Add time and aws profile

diff --git a/bash_prompt b/bash_prompt
--- a/bash_prompt
+++ b/bash_prompt
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # DESCRIPTION:
 #
@@ -20,100 +20,123 @@
 #   https://gist.github.com/31967
 
 # The various escape codes that we can use to color our prompt.
-       BLACK="\[\033[0;30m\]"
- LIGHT_BLACK="\[\033[1;30m\]"
-         RED="\[\033[0;31m\]"
-   LIGHT_RED="\[\033[1;31m\]"
-       GREEN="\[\033[0;32m\]"
- LIGHT_GREEN="\[\033[1;32m\]"
-      YELLOW="\[\033[0;33m\]"
+BLACK="\[\033[0;30m\]"
+LIGHT_BLACK="\[\033[1;30m\]"
+RED="\[\033[0;31m\]"
+LIGHT_RED="\[\033[1;31m\]"
+GREEN="\[\033[0;32m\]"
+LIGHT_GREEN="\[\033[1;32m\]"
+YELLOW="\[\033[0;33m\]"
 LIGHT_YELLOW="\[\033[1;33m\]"
-        BLUE="\[\033[0;34m\]"
-  LIGHT_BLUE="\[\033[1;34m\]"
-      PURPLE="\[\033[0;35m\]"
+BLUE="\[\033[0;34m\]"
+LIGHT_BLUE="\[\033[1;34m\]"
+PURPLE="\[\033[0;35m\]"
 LIGHT_PURPLE="\[\033[1;35m\]"
-        CYAN="\[\033[0;36m\]"
-  LIGHT_CYAN="\[\033[1;36m\]"
-       WHITE="\[\033[0;37m\]"
- LIGHT_WHITE="\[\033[1;37m\]"
-  COLOR_NONE="\[\e[0m\]"
+CYAN="\[\033[0;36m\]"
+LIGHT_CYAN="\[\033[1;36m\]"
+WHITE="\[\033[0;37m\]"
+LIGHT_WHITE="\[\033[1;37m\]"
+COLOR_NONE="\[\e[0m\]"
+
+# determine time
+function parse_datetime() {
+	date | tr -s ' ' | cut -d ' ' -f5
+}
+
+function set_time() {
+	time_str=$(parse_datetime)
+	TIME="${WHITE}(${time_str})${COLOR_NONE} "
+}
 
 # determine git branch name
-function parse_git_branch(){
-  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
+function parse_git_branch() {
+	git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
 }
 
 # determine mercurial branch name
-function parse_hg_branch(){
-  hg branch 2> /dev/null | awk '{print " (" $1 ")"}'
+function parse_hg_branch() {
+	hg branch 2>/dev/null | awk '{print " (" $1 ")"}'
 }
 
 # Determine the branch/state information for this git repository.
 function set_git_branch() {
-  # Get the name of the branch.
-  branch=$(parse_git_branch)
-  # if not git then maybe mercurial
-  if [ "$branch" == "" ]
-  then
-    branch=$(parse_hg_branch)
-  fi
+	# Get the name of the branch.
+	branch=$(parse_git_branch)
+	# if not git then maybe mercurial
+	if [ "$branch" == "" ]; then
+		branch=$(parse_hg_branch)
+	fi
 
-  # Set the final branch string.
-  BRANCH="${CYAN}${branch}${COLOR_NONE} "
+	# Set the final branch string.
+	BRANCH="${CYAN}${branch}${COLOR_NONE} "
 }
 
 function set_k8s_namespace() {
-  kubectl config view --minify -o jsonpath="{.contexts[0].context.namespace}"
+	kubectl config view --minify -o jsonpath="{.contexts[0].context.namespace}"
 }
 
 function set_k8s_context() {
-  kubectl config current-context
+	kubectl config current-context
 }
 
-function set_k8s_prompt () {
-  CONTEXT=$(set_k8s_context)
-  NAMESPACE=$(set_k8s_namespace)
-  K8S="${LIGHT_WHITE}[${PURPLE}${CONTEXT}|${NAMESPACE}${LIGHT_WHITE}]${COLOR_NONE}"
+function set_k8s_prompt() {
+	CONTEXT=$(set_k8s_context)
+	NAMESPACE=$(set_k8s_namespace)
+	K8S="${LIGHT_WHITE}[${PURPLE}${CONTEXT}|${NAMESPACE}${LIGHT_WHITE}]${COLOR_NONE}"
+}
+
+function set_aws_profile() {
+	CURRENT_AWS_PROFILE=" ${WHITE}(${AWS_PROFILE})${COLOR_NONE} "
 }
 
 # Return the prompt symbol to use, colorized based on the return value of the
 # previous command.
-function set_prompt_symbol () {
-  if test $1 -eq 0 ; then
-      PROMPT_SYMBOL="\$"
-  else
-      PROMPT_SYMBOL="${LIGHT_WHITE}\$${COLOR_NONE}"
-  fi
+function set_prompt_symbol() {
+	if test $1 -eq 0; then
+		PROMPT_SYMBOL="\$"
+	else
+		PROMPT_SYMBOL="${LIGHT_WHITE}\$${COLOR_NONE}"
+	fi
 }
 
 # Determine active Python virtualenv details.
 # NOTE: obsolete as we're using conda envs
-function set_virtualenv () {
-  if test -z "$VIRTUAL_ENV" ; then
-      PYTHON_VIRTUALENV=""
-  else
-      PYTHON_VIRTUALENV="${BLUE}[`basename \"$VIRTUAL_ENV\"`]${COLOR_NONE} "
-  fi
+function set_virtualenv() {
+	if test -z "$VIRTUAL_ENV"; then
+		PYTHON_VIRTUALENV=""
+	else
+		PYTHON_VIRTUALENV="${BLUE}[$(basename \"$VIRTUAL_ENV\")]${COLOR_NONE} "
+	fi
+}
+
+function set_conda_env() {
+	CONDA_ENV_PROMPT="${BLUE}${CONDA_PROMPT_MODIFIER}${COLOR_NONE}"
 }
 
 # Set the full bash prompt.
-function set_bash_prompt () {
-  # Set the PROMPT_SYMBOL variable. We do this first so we don't lose the
-  # return value of the last command.
-  set_prompt_symbol $?
+function set_bash_prompt() {
+	set_time
 
-  # Set the PYTHON_VIRTUALENV variable.
-  #set_virtualenv
+	# Set the PROMPT_SYMBOL variable. We do this first so we don't lose the
+	# return value of the last command.
+	set_prompt_symbol $?
 
-  # Set the BRANCH variable.
-  set_git_branch
+	# Set the PYTHON_VIRTUALENV variable.
+	set_virtualenv
+	#set_conda_env
 
-  # set k8s prompt
-  set_k8s_prompt
+	# Set the BRANCH variable.
+	set_git_branch
 
-  # Set the bash prompt variable.
-  PS1="
-${CONDA_PROMPT_MODIFIER} ${YELLOW}\w${COLOR_NONE}${BRANCH}${K8S}
+	# set k8s prompt
+	set_k8s_prompt
+
+	# set AWS profile
+	set_aws_profile
+
+	# Set the bash prompt variable.
+	PS1="
+${TIME}${PYTHON_VIRTUALENV} ${YELLOW}\w${COLOR_NONE}${BRANCH}${K8S}${CURRENT_AWS_PROFILE}
 ${PROMPT_SYMBOL} "
 }
 
